common:
  envName: dev
  name: ml-service
replicaCount: 1
image:
  repository: gcr.io/devops-492107/ml-service
  pullPolicy: IfNotPresent
  tag: '9'
environment: dev
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: fraud-sa
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
healthCheck:
  port: 80
  requestPath: /actuator
service:
  type: NodePort
  port: 80
  targetPort: 8000
httpRoute:
  enabled: false
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.allow-http: 'false'
    kubernetes.io/ingress.regional-static-ip-name: ml-service-static-ip
    kubernetes.io/ingress.class: gce-internal
  hosts:
    - host: ml-service.internal
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: ml-service-tls
      hosts:
        - ml-service.internal
resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi
readinessProbe: null
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
volumes:
  - name: batch-volume
    emptyDir:
      sizeLimit: 1Gi
volumeMounts:
  - name: batch-volume
    mountPath: /data/batch
    readOnly: false
nodeSelector: {}
tolerations: []
affinity: {}
