apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ $.Values.common.envName }}-{{ $.Values.common.name }}

  labels:
    app: {{ $.Values.common.name }}

    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}

    release: {{ $.Release.Name }}

    heritage: {{ $.Release.Service }}

    component: {{ $.Values.common.envName }}-{{ $.Values.common.name }}

    ###########################################################
    # DATADOG UNIFIED TAGGING
    ###########################################################

    tags.datadoghq.com/env: "{{ $.Values.environment }}"

    tags.datadoghq.com/service: "{{ $.Values.common.name }}"

    tags.datadoghq.com/version: "{{ $.Values.image.tag }}"

  #############################################################
  # DATADOG DEPLOYMENT TAGGING
  #############################################################

  annotations:

    ad.datadoghq.com/tags: |
      {
        "env":"{{ $.Values.environment }}",
        "service":"{{ $.Values.common.name }}",
        "version":"{{ $.Values.image.tag }}"
      }

spec:

  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      app: {{ $.Values.common.name }}

      release: {{ $.Release.Name }}

      component: {{ $.Values.common.envName }}-{{ $.Values.common.name }}

      chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}

      heritage: {{ $.Release.Service }}

  template:

    metadata:

      annotations:

        #######################################################
        # DATADOG POD TAGGING
        #######################################################

        tags.datadoghq.com/env: "{{ $.Values.environment }}"

        tags.datadoghq.com/service: "{{ $.Values.common.name }}"

        tags.datadoghq.com/version: "{{ $.Values.image.tag }}"

        ad.datadoghq.com/tags: |
          {
            "env":"{{ $.Values.environment }}",
            "service":"{{ $.Values.common.name }}",
            "version":"{{ $.Values.image.tag }}"
          }

        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      labels:

        app: {{ $.Values.common.name }}

        release: {{ $.Release.Name }}

        component: {{ $.Values.common.envName }}-{{ $.Values.common.name }}

        chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}

        heritage: {{ $.Release.Service }}

        #######################################################
        # DATADOG UNIFIED TAGGING
        #######################################################

        tags.datadoghq.com/env: "{{ $.Values.environment }}"

        tags.datadoghq.com/service: "{{ $.Values.common.name }}"

        tags.datadoghq.com/version: "{{ $.Values.image.tag }}"

    spec:

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ $.Values.serviceAccount.name }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:

        - name: {{ .Chart.Name }}

          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          #####################################################
          # DATADOG ENV VARIABLES
          #####################################################

          env:

            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']

            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']

            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']

            ###################################################
            # ENABLE LOG INJECTION
            ###################################################

            - name: DD_LOGS_INJECTION
              value: "true"

            ###################################################
            # ENABLE PROFILING
            ###################################################

            - name: DD_PROFILING_ENABLED
              value: "true"

            ###################################################
            # ENABLE RUNTIME METRICS
            ###################################################

            - name: DD_RUNTIME_METRICS_ENABLED
              value: "true"

            ###################################################
            # ENABLE TRACE COLLECTION
            ###################################################

            - name: DD_TRACE_ENABLED
              value: "true"

          volumeMounts:
          {{- with .Values.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}