apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Values.common.name }}-internal
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: fraud-cluster-kv-devops-vault
    kind: ClusterSecretStore
  target:
    name: {{ $.Values.common.name }}-internal
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: fraud/dev/generator-ingress-cert
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: fraud/dev/generator-ingress-cert
        property: tls.key