apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Values.common.envName }}-{{ $.Values.common.name }}-db
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: fraud-cluster-kv-dba-vault
    kind: ClusterSecretStore
  target:
    name: {{ $.Values.common.envName }}-{{ $.Values.common.name }}-db
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: MLOps/dev/generator/db
        property: username
    - secretKey: password
      remoteRef:
        key: MLOps/dev/generator/db
        property: password