apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Values.common.envName }}-{{ $.Values.common.name }}-db-certs
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: fraud-cluster-kv-dba-certs-vault
    kind: ClusterSecretStore
  target:
    name: {{ $.Values.common.envName }}-{{ $.Values.common.name }}-db-certs
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: Client_Key.pem
      remoteRef:
        key: MLOps/dev/generator/db
        property: client_key
    - secretKey: Client_cert.pem
      remoteRef:
        key: MLOps/dev/generator/db
        property: client_cert
    - secretKey: root_cert.pem
      remoteRef:
        key: MLOps/dev/generator/db
        property: server_ca_root