apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Values.common.envName }}-{{ $.Values.common.name }}-db-pk8
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: fraud-cluster-kv-devops-vault
    kind: ClusterSecretStore
  target:
    name: {{ $.Values.common.envName }}-{{ $.Values.common.name }}-db-pk8
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: Client_Key.pk8
      remoteRef:
        key: MLOps/dev/generator/dbpk8
        property: Client_key_b64
        decodingStrategy: Base64