replicaCount: 1
image:
  repository: gcr.io/devops-492107/processor
  pullPolicy: IfNotPresent
  tag: '10'
serviceAccount:
  create: false
  name: fraud-ksa
ingress:
  enabled: false
httpRoute:
  enabled: false
service:
  enabled: false
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe: null
readinessProbe: null
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
