affinity: {}
autoscaling:
  enabled: true
  maxReplicas: 8
  minReplicas: 2
  targetCPUUtilizationPercentage: 80
common:
  envName: dev
  name: ecom-frontend
environment: dev
fullnameOverride: ''
healthCheck:
  port: 80
  requestPath: /actuator
httpRoute:
  enabled: false
image:
  pullPolicy: IfNotPresent
  repository: gcr.io/devops-492107/ecommerce-frontend/ecommerce-frontend
  tag: '17'
imagePullSecrets: []
ingress:
  annotations:
    kubernetes.io/ingress.allow-http: 'false'
    kubernetes.io/ingress.class: gce-internal
    kubernetes.io/ingress.regional-static-ip-name: ecom-frontend-static-ip
  enabled: false
  hosts:
  - host: ecom-frontend.internal
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - ecom-frontend.internal
    secretName: ecom-frontend-tls
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
readinessProbe: null
replicaCount: 4
resources:
  limits:
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 1Gi
securityContext: {}
service:
  port: 80
  targetPort: 3000
  type: LoadBalancer
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: fraud-ksa
tolerations: []
volumeMounts:
- mountPath: /data/batch
  name: batch-volume
  readOnly: false
volumes:
- emptyDir:
    sizeLimit: 1Gi
  name: batch-volume
