common:
  envName: dev
  name: ecom-frontend
replicaCount: 1
image:
  repository: gcr.io/devops-492107/ecommerce-frontend/ecommerce-frontend
  pullPolicy: IfNotPresent
  tag: '17'
environment: dev
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: fraud-ksa
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
healthCheck:
  port: 8080
  requestPath: /actuator
service:
  type: NodePort
  port: 80
  targetPort: 8080
httpRoute:
  enabled: false
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.allow-http: 'false'
    kubernetes.io/ingress.regional-static-ip-name: ecom-frontend-static-ip
    kubernetes.io/ingress.class: gce-internal
  hosts:
    - host: ecom-frontend.internal
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: ecom-frontend-tls
      hosts:
        - ecom-frontend.internal
resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi
readinessProbe: null
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
volumes:
  - name: batch-volume
    emptyDir:
      sizeLimit: 1Gi
volumeMounts:
  - name: batch-volume
    mountPath: /data/batch
    readOnly: false
nodeSelector: {}
tolerations: []
affinity: {}
